$ErrorActionPreference = "Stop"
New-Item -ItemType Directory -Force -Path ".\assets\images" | Out-Null
function Download($url, $out) { Invoke-WebRequest -Uri $url -OutFile ".\assets\images\$out" -UseBasicParsing }
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/5156/divrigi-ulu-camii-ve-darussifasi-cennet-kapi" "5156-cennet-kapi.jpg"
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/5157/divrigi" "5157-genel.jpg"
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/5149/divrigi" "5149-detay.jpg"
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/5155/divrigi" "5155-bezemeler.jpg"
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/5154/divrigi" "5154-oyma.jpg"
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/5153/divrigi" "5153-portal.jpg"
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/5152/divrigi" "5152-kemer.jpg"
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/5151/divrigi" "5151-yazi-motif.jpg"
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/5147/divrigi" "5147-cephe.jpg"
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/5146/divrigi" "5146-portal2.jpg"
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/5145/divrigi" "5145-genel2.jpg"
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/3951/divrigi" "3951-ic.jpg"
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/3949/divrigi" "3949-detay.jpg"
# Detail pages
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/5156/divrigi-ulu-camii-ve-darussifasi-cennet-kapi" "ck-1.jpg"
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/5154/divrigi" "bk-1.jpg"
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/5153/divrigi" "bk-2.jpg"
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/5146/divrigi" "s-1.jpg"
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/3951/divrigi" "mm-1.jpg"
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/5149/divrigi" "mm-2.jpg"
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/5152/divrigi" "d-1.jpg"
Download "https://www.kulturportali.gov.tr/medya/fotograf/fotodokuman/5151/divrigi" "d-2.jpg"
Write-Host "✓ Görseller indirildi: .\assets\images"
